/**
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    /**
     * Some library description.
     * @return <code>true</code>
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
