/**
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.assertTrue;

/**
 * This Java source file was generated by the Gradle 'init' task.
 */
public class LibraryTest {

    /**
    * @Test.
    */
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
